spring.application.name=api
server.port=8090
#spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
#spring.datasource.username=${DB_USER}
#spring.datasource.password=${DB_PW}
spring.datasource.url = jdbc:postgresql://localhost:5432/TBD_LAB2
spring.datasource.username=postgres
spring.datasource.password=Claire12261510
spring.datasource.driver-class-name=org.postgresql.Driver
jwt.secret=$2a$10$kKBlJYCM1FrHLd1ESc2Q/OoK5jfNSMr/gjVRzSJeFVrZcmtaXEPVW
jwt.expiration=3600000
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.spatial.connection_finder=org.hibernate.spatial.dialect.postgis.PostgisConnectionFinder